CREATE TABLE IF NOT EXISTS promotions (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	code VARCHAR(20) NOT NULL UNIQUE,
	name VARCHAR(50) NOT NULL,
	discount_percentage DECIMAL(5,2) NULL,
	discount_amount int NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
