//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Promotions = newPromotionsTable("ginapp_2", "promotions", "")

type promotionsTable struct {
	mysql.Table

	// Columns
	ID                 mysql.ColumnInteger
	Code               mysql.ColumnString
	Name               mysql.ColumnString
	DiscountPercentage mysql.ColumnFloat
	DiscountAmount     mysql.ColumnInteger
	Status             mysql.ColumnInteger // 0: inactive, 1: active
	CreatedAt          mysql.ColumnTimestamp
	UpdatedAt          mysql.ColumnTimestamp

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
	DefaultColumns mysql.ColumnList
}

type PromotionsTable struct {
	promotionsTable

	NEW promotionsTable
}

// AS creates new PromotionsTable with assigned alias
func (a PromotionsTable) AS(alias string) *PromotionsTable {
	return newPromotionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PromotionsTable with assigned schema name
func (a PromotionsTable) FromSchema(schemaName string) *PromotionsTable {
	return newPromotionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PromotionsTable with assigned table prefix
func (a PromotionsTable) WithPrefix(prefix string) *PromotionsTable {
	return newPromotionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PromotionsTable with assigned table suffix
func (a PromotionsTable) WithSuffix(suffix string) *PromotionsTable {
	return newPromotionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPromotionsTable(schemaName, tableName, alias string) *PromotionsTable {
	return &PromotionsTable{
		promotionsTable: newPromotionsTableImpl(schemaName, tableName, alias),
		NEW:             newPromotionsTableImpl("", "new", ""),
	}
}

func newPromotionsTableImpl(schemaName, tableName, alias string) promotionsTable {
	var (
		IDColumn                 = mysql.IntegerColumn("id")
		CodeColumn               = mysql.StringColumn("code")
		NameColumn               = mysql.StringColumn("name")
		DiscountPercentageColumn = mysql.FloatColumn("discount_percentage")
		DiscountAmountColumn     = mysql.IntegerColumn("discount_amount")
		StatusColumn             = mysql.IntegerColumn("status")
		CreatedAtColumn          = mysql.TimestampColumn("created_at")
		UpdatedAtColumn          = mysql.TimestampColumn("updated_at")
		allColumns               = mysql.ColumnList{IDColumn, CodeColumn, NameColumn, DiscountPercentageColumn, DiscountAmountColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
		mutableColumns           = mysql.ColumnList{CodeColumn, NameColumn, DiscountPercentageColumn, DiscountAmountColumn, StatusColumn, CreatedAtColumn, UpdatedAtColumn}
		defaultColumns           = mysql.ColumnList{StatusColumn, CreatedAtColumn, UpdatedAtColumn}
	)

	return promotionsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		Code:               CodeColumn,
		Name:               NameColumn,
		DiscountPercentage: DiscountPercentageColumn,
		DiscountAmount:     DiscountAmountColumn,
		Status:             StatusColumn,
		CreatedAt:          CreatedAtColumn,
		UpdatedAt:          UpdatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
