//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type OrderDetails struct {
	ID        int64 `sql:"primary_key"`
	OrderID   int64
	ItemID    int64
	Quantity  int32
	Price     int32
	CreatedAt *time.Time
	UpdatedAt *time.Time
}
