//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Promotions struct {
	ID                 int64 `sql:"primary_key"`
	Code               string
	Name               string
	DiscountPercentage *float64
	DiscountAmount     *int32
	Status             uint8 // 0: inactive, 1: active
	CreatedAt          *time.Time
	UpdatedAt          *time.Time
}
